version: '3.8'

services:
  web:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - ./webapp:/usr/src/app/webfactory

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5432:5432

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./webapp
    command: celery -A webapp worker --loglevel=info
    depends_on:
      - web
      - redis
    env_file:
      - ./.env.dev
    volumes:
      - ./webapp:/usr/src/app/webapp

  flower:
    image: mher/flower
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - FLOWER_PORT=5555
    ports:
        - 5555:5555
    depends_on:
        - redis

volumes:
  postgres_data:
