version: '3.8'

services:
  web:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - ./webapp:/usr/src/app/webfactory

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5432:5432

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080



volumes:
  postgres_data:
