# Generated by Django 4.2.3 on 2023-08-17 15:27

import django.utils.timezone
from django.conf import settings
from django.core import serializers
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WorkZoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buildingmodel')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.toolmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProducedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parts_produced', models.PositiveIntegerField()),
                ('comments', models.CharField(blank=True, max_length=1080)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_last_hour', models.BooleanField(default=True)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                             to=settings.AUTH_USER_MODEL)),
                ('working_zome',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workzonemodel')),
            ],
        ),
    ]
